version: 2
jobs:
  build:
    # This doesn't work, because gh-pages branch doesn't have .circleci config
    # branches:
    #   ignore:
    #     - gh-pages
    docker:
      - image: circleci/node:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - '47:7c:1d:a1:ac:b7:65:ae:49:c4:7a:3e:0e:eb:49:d9'

      - checkout

      - restore_cache:
          key: node-modules-{{ checksum "yarn.lock" }}

      - run: yarn

      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run: yarn build

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git config --global user.email tomas.ehrlich@gmail.com
              git config --global user.name "Tomáš Ehrlich"
              yarn deploy
            fi
